version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
clone_depth: 5
init:
- cmd: set PATH=C:\Python35;C:\Python35\Scripts;%path%
environment:
  latestcommit: false
  notifyall: true
before_build:
- ps: |
    git clone -q --depth=5 --branch=master https://github.com/kwsch/PKHeX.git C:\projects\pkhex
    Set-Location -Path "C:\projects\pkhex\pkhex.winforms"
    Copy-Item "C:\projects\pkhex-auto-legality-mod\AutoLegality" "C:\projects\pkhex\pkhex.winforms" -recurse
    Copy-Item "C:\projects\pkhex-auto-legality-mod\Addons (Optional)\PGL QR Auto Legality\PGLRentalLegality" "C:\projects\pkhex\pkhex.winforms" -recurse
    Copy-Item "C:\projects\pkhex-auto-legality-mod\Addons (Optional)\MGDB Downloader\MGDBDownloader" "C:\projects\pkhex\pkhex.winforms" -recurse
    Copy-Item "C:\projects\pkhex-auto-legality-mod\Addons (Optional)\URL Genning\URLGenning" "C:\projects\pkhex\pkhex.winforms" -recurse
    Copy-Item "C:\projects\pkhex-auto-legality-mod\Addons (Optional)\Export Trainer Data\ExportTrainerData" "C:\projects\pkhex\pkhex.winforms" -recurse
    Copy-Item "C:\projects\pkhex-auto-legality-mod\Addons (Optional)\Smogon Genner\SmogonGenner" "C:\projects\pkhex\pkhex.winforms" -recurse
    Copy-Item "C:\projects\pkhex-auto-legality-mod\Addons (Optional)\Legalize Boxes\LegalizeBoxes" "C:\projects\pkhex\pkhex.winforms" -recurse
    Copy-Item C:\projects\pkhex-auto-legality-mod\build-mod.py C:\projects\pkhex\pkhex.winforms
    pip3.5 install lxml==4.2.2
    python build-mod.py
    Set-Location -Path "C:\projects\pkhex"
    $env:pkhex_commit = $(git rev-parse --short HEAD)
    $env:mod_commit = $env:APPVEYOR_REPO_COMMIT.Substring(0,7)
    Add-AppveyorMessage $env:pkhex_commit
    Add-AppveyorMessage $env:mod_commit
    if ($env:notifyall -eq "true") { Add-AppveyorMessage "notify" }
    nuget restore
build_script:
- ps: msbuild C:\projects\pkhex\PKHeX.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /verbosity:minimal /p:DefineConstants=UNSAFEDLL /p:Configuration=Release
before_package:
- cmd: xcopy C:\projects\pkhex\pkhex.winforms\bin\release C:\projects\pkhex-auto-legality-mod\bin /e /i /h
after_build:
- cmd: >-
    xcopy  C:\projects\pkhex\pkhex.winforms\bin\release C:\projects\pkhex-auto-legality-mod\bin /e /i /h
artifacts:
- path: bin
  name: PKHeX-$(pkhex_commit)-Auto-Legality-Mod-$(mod_commit)
